import { Colors } from '@constants/styles/colors';

import { ICommonTheme, ITheme } from './types';

const commonTheme: ICommonTheme = {
  fontWeights: {
    xxs: 200,
    xs: 300,
    s: 400,
    m: 500,
    l: 600,
    xl: 700,
  },
  fontSizes: {
    xxs: 10,
    xs: 16,
    s: 26,
    m: 30,
    xl: 65,
    xxl: 75,
  },
  colors: {
    DARK_BG: Colors.DARK_BG,
    LIGHT_BG: Colors.LIGHT_BG,
    MODAL_BG: Colors.MODAL_BG,
    TEXT_GRADIENT_GREEN: Colors.TEXT_GRADIENT_GREEN,
    IMAGE_GRADIENT_GREEN: Colors.IMAGE_GRADIENT_GREEN,
    BOX_GRADIENT_BLACK: Colors.BOX_GRADIENT_BLACK,
    GREEN: Colors.GREEN,
    WHITE: Colors.WHITE,
    LIGHT_GRAY: Colors.LIGHT_GRAY,
    GRAY: Colors.GRAY,
    MEDIUM_GRAY: Colors.MEDIUM_GRAY,
    DARK_GRAY: Colors.DARK_GRAY,
    FOOTER_GRAY: Colors.FOOTER_GRAY,
    SEARCH_LIGHT_GRAY: Colors.SEARCH_LIGHT_GRAY,
    SEARCH_DARK_GRAY: Colors.SEARCH_DARK_GRAY,
    RED: Colors.RED,
  },
  dimensions: {
    mobile: 495,
  },
  borderRadiuses: {
    xs: 4,
    s: 8,
    m: 10,
    l: 20,
    xl: 50,
  },
  margins: {
    zero: 0,
    five: 5,
    ten: 10,
    twenty: 20,
    thirty: 30,
    thirtyFive: 35,
    fourty: 40,
    fourtyFive: 45,
    fifty: 50,
    eighty: 80,
    hundred: 100,
    hundredTwenty: 120,
    twoHundreds: 200,
    twoHundredsTen: 210,
  },
  paddings: {
    zero: 0,
    one: 1,
    five: 5,
    ten: 10,
    fifteen: 15,
    eighteen: 18,
    twenty: 20,
    twentyFive: 25,
    thirty: 30,
    thirtyFive: 35,
    fourty: 40,
    fourtyFive: 45,
    fifty: 50,
    sixty: 60,
    eighty: 80,
    hundred: 100,
    twoHundredsTen: 210,
  },
  top: {
    zero: 0,
    one: 1,
    five: 5,
    fifteen: 15,
    fifty: 50,
    hundred: 100,
  },
  right: {
    fifteen: 15,
  },
  left: {
    zero: 0,
    fifteen: 15,
    twenty: 20,
    fifty: 50,
  },
  bottom: {
    three: 3,
    eight: 8,
    thirty: 30,
  },
  opacities: {
    zero: 0,
    dotOne: 0.1,
    dotTwo: 0.2,
    dotFive: 0.5,
    dotSeven: 0.7,
    dotNine: 0.9,
    one: 1,
  },
  zIndexes: {
    one: 1,
    thousand: 1000,
  },
  width: {
    zero: 0,
    seven: 7,
    ten: 10,
    fifteen: 15,
    sixteen: 16,
    twenty: 20,
    twentyFive: 25,
    thirty: 30,
    fourty: 40,
    fifty: 50,
    fiftyFive: 55,
    sixty: 60,
    eighty: 80,
    eightyFive: 85,
    ninety: 90,
    hundred: 100,
    hundredTen: 110,
    hundredFourty: 140,
    hundredEighty: 180,
    twoHundred: 200,
    twoHundredFifty: 250,
    threeHundredFifty: 350,
    fourHundred: 400,
    fourHundredEighty: 480,
  },
  height: {
    one: 1,
    three: 3,
    seven: 7,
    ten: 10,
    fifteen: 15,
    sixteen: 16,
    nineteen: 19,
    twenty: 20,
    twentyFive: 25,
    thirty: 30,
    fourty: 40,
    fourtyFive: 45,
    fifty: 50,
    fiftyFive: 55,
    seventy: 70,
    eighty: 80,
    ninety: 90,
    hundred: 100,
    hundredTwenty: 120,
    hundredFifty: 150,
    hundredSeventy: 170,
    hundredEighty: 180,
    twoHundredFifty: 250,
    threeHundred: 300,
    threeHundredEighty: 380,
    fourHundredSixty: 460,
  },
};

export const darkTheme: ITheme = {
  bodyColor: Colors.DARK_BG,
  fontColor: Colors.LIGHT_BG,
  subtitleColor: Colors.LIGHT_GRAY,
  currencyCardColor: Colors.DARK_GRAY,
  ...commonTheme,
};
export const lightTheme: ITheme = {
  bodyColor: Colors.LIGHT_BG,
  fontColor: Colors.DARK_BG,
  subtitleColor: Colors.DARK_GRAY,
  currencyCardColor: Colors.MEDIUM_GRAY,
  ...commonTheme,
};
