name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: install modules
        run: yarn
      - name: build project
        run: yarn run build
